server:
  port: 9000
spring:
  application:
    name: "@pom.artifactId@"
  config:
    import: 'file:etc/app.properties'
  datasource:
    url: jdbc:mysql://localhost:3306/mzzb_server
    username: mzzb_server
    password: mzzb_server
  jpa:
    open-in-view: true
    generate-ddl: true
    properties:
      hibernate.format_sql: true
      hibernate.auto_quote_keyword: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
---
spring:
  config:
    activate:
      on-profile: dev
  activemq:
    broker-url: tcp://localhost:61616
    password: admin
    user: admin
  jpa:
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: prod
  activemq:
    broker-url: tcp://localhost:61616
    password: ${activemq.password:admin}
    user: admin
