server:
  port: 9000
spring:
  config:
    import: file:etc/app.properties
  datasource:
    url: jdbc:mysql://localhost:3306/mzzb_server
    username: mzzb_server
    password: mzzb_server
  jpa:
    open-in-view: true
    generate-ddl: true
    properties:
      hibernate.format_sql: true
      hibernate.auto_quote_keyword: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
---
spring:
  config:
    activate:
      on-profile: dev
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: prod
  rabbitmq:
    host: ${rabbitmq.host:127.0.0.1}
    port: ${rabbitmq.port:5672}
    username: ${rabbitmq.username:guest}
    password: ${rabbitmq.password:guest}
