server:
  port: 9090
spring:
  application:
    name: "@pom.artifactId@"
  config:
    import: 'file:etc/app.properties'
  datasource:
    url: jdbc:mysql://localhost:3306/mzzb_server
    username: mzzb_server
    password: mzzb_server
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
---
spring:
  config:
    activate:
      on-profile: prod
  activemq:
    broker-url: tcp://localhost:61616
    password: ${activemq.password}
    user: admin
