DROP DATABASE IF EXISTS mzzb_pro;
DROP USER IF EXISTS 'mzzb_pro'@'localhost';

DROP DATABASE IF EXISTS mzzb_dev;
DROP USER IF EXISTS 'mzzb_dev'@'localhost';

CREATE DATABASE mzzb_pro
  CHARSET utf8;
CREATE USER 'mzzb_pro'@'localhost'
  IDENTIFIED BY 'mzzb_pro';
GRANT ALL PRIVILEGES ON mzzb_pro.* TO 'mzzb_pro'@'localhost';

CREATE DATABASE mzzb_dev
  CHARSET utf8;
CREATE USER 'mzzb_dev'@'localhost'
  IDENTIFIED BY 'mzzb_dev';
GRANT ALL PRIVILEGES ON mzzb_dev.* TO 'mzzb_dev'@'localhost';

FLUSH PRIVILEGES;

USE mzzb_dev;

CREATE TABLE SPRING_SESSION (
  SESSION_ID            CHAR(36),
  CREATION_TIME         BIGINT NOT NULL,
  LAST_ACCESS_TIME      BIGINT NOT NULL,
  MAX_INACTIVE_INTERVAL INT    NOT NULL,
  PRINCIPAL_NAME        VARCHAR(100),
  CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (SESSION_ID)
)
  ENGINE = InnoDB;

CREATE INDEX SPRING_SESSION_IX1
  ON SPRING_SESSION (LAST_ACCESS_TIME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
  SESSION_ID      CHAR(36),
  ATTRIBUTE_NAME  VARCHAR(200),
  ATTRIBUTE_BYTES BLOB,
  CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_ID, ATTRIBUTE_NAME),
  CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_ID) REFERENCES SPRING_SESSION (SESSION_ID)
    ON DELETE CASCADE
)
  ENGINE = InnoDB;

CREATE INDEX SPRING_SESSION_ATTRIBUTES_IX1
  ON SPRING_SESSION_ATTRIBUTES (SESSION_ID);
USE mzzb_pro;

CREATE TABLE SPRING_SESSION (
  SESSION_ID            CHAR(36),
  CREATION_TIME         BIGINT NOT NULL,
  LAST_ACCESS_TIME      BIGINT NOT NULL,
  MAX_INACTIVE_INTERVAL INT    NOT NULL,
  PRINCIPAL_NAME        VARCHAR(100),
  CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (SESSION_ID)
)
  ENGINE = InnoDB;

CREATE INDEX SPRING_SESSION_IX1
  ON SPRING_SESSION (LAST_ACCESS_TIME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
  SESSION_ID      CHAR(36),
  ATTRIBUTE_NAME  VARCHAR(200),
  ATTRIBUTE_BYTES BLOB,
  CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_ID, ATTRIBUTE_NAME),
  CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_ID) REFERENCES SPRING_SESSION (SESSION_ID)
    ON DELETE CASCADE
)
  ENGINE = InnoDB;

CREATE INDEX SPRING_SESSION_ATTRIBUTES_IX1
  ON SPRING_SESSION_ATTRIBUTES (SESSION_ID);
